```{r}
library(tidyverse)
library(usethis)
```

```{r}
refine_aerobic_status_values <- function (df) {
  df %>%
    mutate(aerobic_status = case_when(
      aerobic_status == "anaerobe (unspecified)" ~ "obligate anaerobe",
      # Assume that organisms filed under "microaerobe" and "microaerobe or
      # anaerobe" have genes to neutralize O2 but do not carry out aerobic
      # respiration
      aerobic_status == "microaerobe" ~ "obligate anaerobe",
      aerobic_status == "microaerobe or anaerobe" ~ "obligate anaerobe",
      # Assume that organisms filed under "microaerobe or aerobe" can carry out
      # aerobic respiration
      aerobic_status == "microaerobe or aerobe" ~ "aerobe",
      # This is a facultative anaerobe if I ever saw one
      aerobic_status == "aerobe, microaerobe, or anaerobe" ~ "facultative anaerobe",
      # Likewise, assume "aerotolerant" means facultative anaerobe
      aerobic_status == "aerotolerant" ~ "facultative anaerobe",
      # The labels "variable" and "not indicated" do not help us here; we need
      # definite answers
      aerobic_status == "variable" ~ NA_character_,
      aerobic_status == "not indicated" ~ NA_character_,
      TRUE ~ aerobic_status))
}
refine_gram_stain_values <- function (df) {
  df %>%
    mutate(gram_stain = case_when(
      gram_stain == "Gram-variable" ~ NA_character_,
      gram_stain == "not indicated" ~ NA_character_,
      TRUE ~ gram_stain))
}
```


```{r message=FALSE}
##manually curated genus phenotypes from Ceylan
genus_phenotypes <- read_tsv("genera_0831.txt", na = "N/A") %>%
  mutate(rank = "Genus") %>%
  select(taxon = name, rank, aerobic_status, gram_stain, doi) %>%
  refine_aerobic_status_values() %>%
  refine_gram_stain_values() %>%
  filter(!(is.na(aerobic_status) & is.na(gram_stain)))

genus_phenotypes %>%
  count(aerobic_status)
genus_phenotypes %>%
  count(gram_stain)
```

```{r message=FALSE}
species_phenotypes <- read_tsv("species_0831.txt", na = "N/A") %>%
  mutate(rank = "Species") %>%
  select(taxon = name, rank, aerobic_status, gram_stain, doi) %>%
  refine_aerobic_status_values() %>%
  refine_gram_stain_values() %>%
  filter(!(is.na(aerobic_status) & is.na(gram_stain)))

species_phenotypes %>%
  count(taxon) %>%
  filter(n > 1)
species_phenotypes %>%
  count(aerobic_status)
species_phenotypes %>%
  count(gram_stain)
```

```{r}
misc_phenotypes <- read_csv("phenotype_misc.csv")
```


```{r}
taxon_phenotypes <- bind_rows(
  misc_phenotypes, genus_phenotypes, species_phenotypes)
taxon_phenotypes %>%
  count(rank)
taxon_phenotypes %>%
  count(aerobic_status)
taxon_phenotypes %>%
  count(gram_stain)
```

TODO: Check for consistency between genus and species.

```{r}
usethis::use_data(taxon_phenotypes, overwrite = T)
```

Include Lactobacillus species that are vancomycin-sensitive here. All
Lactobacillus strains are considered facultative anaerobes, though they might
be grown under various conditions

```{r eval=FALSE}
##manually curated lactobacillus database from paper
lactobacillus_species <- read_csv( "Lactobacillus_data.csv") %>%
  select(taxon = name, rank, vancomycin, doi) %>%
  mutate(vancomycin = if_else(vancomycin, "sensitive", "resistant"))

##vancomycin resistance

abx_idx_df[nrow(abx_idx_df)+1,] <- list("vancomycin", FALSE, "Lactobacillus", "Genus", "10.1128/AEM.01738-18")
abx_idx_df[nrow(abx_idx_df)+1,] <- list("vancomycin", FALSE, "Leuconostoc", "Genus", "10.1053/jhin.1998.0605")
abx_idx_df[nrow(abx_idx_df)+1,] <- list("vancomycin", FALSE, "Pediococcus", "Genus", "10.1053/jhin.1998.0605")
abx_idx_df[nrow(abx_idx_df)+1,] <- list("vancomycin", FALSE, "Erysipelothrix", "Genus", "10.1053/jhin.1998.0605")

#vancomycin resistance for enterococci are due to intrinsic expression of van genes
vanco_entero_except <- c("Enterococcus gallinarum",
                         "Enterococcus casseliflavus",
                         "Enterococcus flavescens")
for(entero in vanco_entero_except){
  abx_idx_df[nrow(abx_idx_df)+1,] <- list("vancomycin", FALSE, entero, "Species", "10.1016/j.jiac.2018.01.001") ##resistant
}

abx_idx_df[nrow(abx_idx_df)+1,] <- list("vancomycin", FALSE, "Mycoplasma", "Genus", "10.1038/nrmicro1464")

##anaerobes
abx_idx_df[nrow(abx_idx_df)+1,] <- list("anaerobe", TRUE, "Bacteroidales", "Order", "10.1128/microbiolspec.dmih2-0015-2015")
abx_idx_df[nrow(abx_idx_df)+1,] <- list("anaerobe", FALSE, "Salmonella", "Genus", "10.1002/9781118960608.gbm01166")
abx_idx_df[nrow(abx_idx_df)+1,] <- list("anaerobe", FALSE, "Listeria", "Genus", "10.1002/9781118960608.gbm00547")
anaerobe <- c("Actinomyces",
              "Peptostreptococcus",
              "Finegoldia",
              "Parvimonas",
              "Bifidobacterium")
for(ana in anaerobe){
  abx_idx_df[nrow(abx_idx_df)+1,] <- list("anaerobe", TRUE, ana, "Genus", "10.1128/microbiolspec.dmih2-0015-2015")
}

##aerobes
abx_idx_df[nrow(abx_idx_df)+1,] <- list("aerobe", FALSE, "Bacteroidales", "Order", "10.1128/microbiolspec.dmih2-0015-2015")
abx_idx_df[nrow(abx_idx_df)+1,] <- list("aerobe", FALSE, "Salmonella", "Genus", "10.1002/9781118960608.gbm01166")
abx_idx_df[nrow(abx_idx_df)+1,] <- list("aerobe", FALSE, "Listeria", "Genus", "10.1002/9781118960608.gbm00547")
for(ana in anaerobe){
  abx_idx_df[nrow(abx_idx_df)+1,] <- list("aerobe", FALSE, ana, "Genus", "10.1128/microbiolspec.dmih2-0015-2015")
}

##tetracycline
tet_intrins_resist_replace <- c("Escherichia coli",
                                "Enterococcus faecalis",
                                "Pseudomonas aeruginosa",
                                "Staphylococcus aureus",
                                "Stenotrophomonas maltophilia")
for(tet_replace in tet_intrins_resist_replace){
  abx_idx_df[nrow(abx_idx_df)+1,] <- list("tetracycline", FALSE, tet_replace, "Species", "10.1101/cshperspect.a025387")
}

abx_idx_df[nrow(abx_idx_df)+1,] <- list("tetracycline", FALSE, "Pseudomonas", "Genus", "10.1101/cshperspect.a025387")

tet_intrins_resist_species <- c("Bacteroides fragilis",
                                "Enterobacter cloacae",
                                "Acinetobacter baumannii",
                                "Klebsiella pneumoniae", ##Klebsiella generally susceptible
                                "Proteus mirabilis",
                                "Serratia marcescens")
for(tet_species in tet_intrins_resist_species){
  abx_idx_df[nrow(abx_idx_df)+1,] <- list("tetracycline", FALSE, tet_species, "Species", "10.1101/cshperspect.a025387")
}

enterobacter_resist_species <- c("Enterobacter asburiae",
                                "Enterobacter bugandensis",
                                "Enterobacter aerogenes")
for(ent_tet_species in enterobacter_resist_species){
  abx_idx_df[nrow(abx_idx_df)+1,] <- list("tetracycline", FALSE, ent_tet_species, "Species", "10.1128/CMR.00002-19")
}


tet_gtpase_species <- c("Agrobacterium tumefaciens",
                       "Bacillus anthracis",
                       "Bacillus cereus",
                       "Bacillus thuringiensis",
                       "Bacteroides fragilis",
                       "Bifidobacterium longum",
                       "Clostridium acetobutylicum",
                       "Clostridium perfringens",
                       "Lactobacillus johnsonii",
                       "Lactobacillus plantarum",
                       "Streptococcus agalactiae",
                       "Streptomyces avermitilis",
                       "Streptomyces coelicolor")

for(gtpase_species in tet_gtpase_species){
  abx_idx_df[nrow(abx_idx_df)+1,] <- list("tetracycline", FALSE, gtpase_species, "Species", "10.1186/1471-2164-8-15")
}

abx_idx_df[nrow(abx_idx_df)+1,] <- list("tetracycline", FALSE, "Salmonella typhimurium", "Species", "10.1038/nrmicro1464")
abx_idx_df[nrow(abx_idx_df)+1,] <- list("tetracycline", FALSE, "Campylobacter jejuni", "Species", "10.1038/nrmicro1464")
abx_idx_df[nrow(abx_idx_df)+1,] <- list("tetracycline", FALSE, "Bacteroides", "Genus", "10.1128/mBio.00569-13") ##tetracycline resistance among Bacteroides is widely distributed
abx_idx_df[nrow(abx_idx_df)+1,] <- list("tetracycline", TRUE, "Klebsiella", "Genus", "10.1101/cshperspect.a025387")
abx_idx_df[nrow(abx_idx_df)+1,] <- list("tetracycline", FALSE, "Mycobacterium abscessus", "Species", "10.1128/AAC.00119-18")

##penicillin
abx_idx_df[nrow(abx_idx_df)+1,] <- list("penicillin", FALSE, "Bacteroides", "Genus", "10.3934/microbiol.2018.3.482")

##these resistant organisms usually do not have a permeable outer membrane
abx_idx_df[nrow(abx_idx_df)+1,] <- list("penicillin", FALSE, "Stenotrophomonas maltophilia", "Species", "10.1186/s13054-019-2371-3")
abx_idx_df[nrow(abx_idx_df)+1,] <- list("penicillin", FALSE, "Enterococcus faecalis", "Species", "10.4161/viru.21282")
abx_idx_df[nrow(abx_idx_df)+1,] <- list("penicillin", FALSE, "Enterococcus faecium", "Species", "10.4161/viru.21282")
abx_idx_df[nrow(abx_idx_df)+1,] <- list("penicillin", FALSE, "Escherichia coli", "Species", "10.1016/j.ijmm.2013.02.009")

abx_idx_df[nrow(abx_idx_df)+1,] <- list("penicillin", FALSE, "Mycoplasma", "Genus", "10.1038/nrmicro1464")

##aminoglycoside
abx_idx_df[nrow(abx_idx_df)+1,] <- list("aminoglycoside", TRUE, "Staphylococcus", "Genus", "10.1136/archdischild-2015-309069")

abx_idx_df <- as.data.frame(abx_idx_df)

#save this df as data to use in package
usethis::use_data(abx_idx_df, overwrite = TRUE)


##review paper on drug class: https://doi.org/10.1016/j.bcp.2017.01.003
##Tet protection genes on mobile elements: http://faculty.washington.edu/marilynr/, https://doi.org/10.1016/j.femsle.2005.02.034
##the Clinical and Laboratory Standards Institute (CLSI) guidelines assesses abx resistance


abx_test_df <- data.frame(a = c(0.1, 0.4, 0.1, 0.3, 0.1),
                          b = c(0, 0.25, 0.25, 0.25, 0.25),
                          c = c(1, 0, 0, 0, 0),
                          d = c(0, 0, 1, 0, 0))
row.names(abx_test_df) <- c("k__Bacteria; p__Actinobacteria; c__; o__; f__; g__; s__",
                        "k__Bacteria; p__Firmicutes; c__Clostridia; o__Clostridiales; f__Clostridiaceae; g__Clostridium; s__Clostridium perfringens",
                        "k__Bacteria; p__Firmicutes; c__Bacilli; o__Lactobacillales; f__Enterococcaceae; g__Enterococcus; s__Enterococcus gallinarum",
                        "k__Bacteria; p__Firmicutes; c__Negativicutes; o__Veillonellales; f__Veillonellaceae; g__Veillonella",
                        "k__Bacteria; p__Proteobacteria; c__Gammaproteobacteria; o__Pseudomonadales; f__Pseudomonadaceae; g__; s__"
)

usethis::use_data(abx_test_df, overwrite = TRUE)
```
